export type UserProfileDto = {
    steamId: string;
    nickname: string;
    avatarUrl: string | null;
    profileImageUrl: string | null;
    firstName: string | null;
    lastName: string | null;
    email: string | null;
    birthDate: string | null;
    address: string | null;
    zipCode: string | null;
    city: string | null;
    countryCode: string | null;
    phone: string | null;
    discord: string | null;
    twitter: string | null;
    hltv: string | null;
    customUsername: string | null;
    timezone: string | null;
    profileCompleted: boolean;
    createdAt: string | null;
    updatedAt: string | null;
};

export type UserProfileUpdateDto = {
    customUsername?: string | null;
    firstName?: string | null;
    lastName?: string | null;
    email?: string | null;
    birthDate?: string | null;
    address?: string | null;
    zipCode?: string | null;
    city?: string | null;
    countryCode?: string | null;
    phone?: string | null;
    twitter?: string | null;
    discord?: string | null;
    hltv?: string | null;
    timezone?: string | null;
};
